name: Deploy production to AWS

on: 
  push:
    branches:
      - master

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: npm install and build webpack
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/

  deploy-source-to-production:
    name: Deploy source code to AWS
    needs: build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public

      - name: Push source code to AWS
        uses:  github/deploy-nodejs@master
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

  deploy-docker-image-to-production:
    name: Docker build, tag, and push
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v1
        
      - name: Download build artifacts
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public

      - name: Push docker image to AWS
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: production-nginx-image
