name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgenteluci/cloudformation-deploy-action@v1.4.0
      env:
        AWS_STACK_NAME: 'vdoster'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.VDOSTER_AWS_DEPLOY_BUCKET}}
        PARAMETER_OVERRIDES: AliasName=prod
